font-family = DankMono Nerd Font
font-size = 20
theme = catppuccin-macchiato
shell-integration-features = no-cursor,no-title
cursor-style = block
adjust-cell-height = 55%
macos-titlebar-style = transparent
window-theme = dark
