font-family = Iosevka Custom
font-size = 21
theme = Catppuccin Mocha
shell-integration-features = no-cursor,no-title
cursor-style = block
adjust-cell-height = 20%
macos-titlebar-style = hidden
window-theme = dark
background-opacity = 0.95
background-blur-radius = 20 
title = ""
window-decoration = auto
window-padding-x = 10
window-padding-y = 10
window-padding-balance = true
window-height = 40
window-width = 170
macos-option-as-alt = left
keybind = opt+grave_accent=text:`
keybind = shift+opt+grave_accent=text:~
mouse-hide-while-typing = true
