font-size = 20
font-family = SFMono Nerd Font
font-size = 20
theme = Catppuccin Mocha
cursor-style = block
adjust-cell-height = 55%
macos-titlebar-style = hidden
shell-integration-features = no-cursor,no-title
window-theme = dark
title = ""
window-padding-x = 20
window-padding-y = 4
window-padding-balance = true
window-height = 52
window-width = 162
