"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout=100000

format = "$all"
right_format = """
$os\
$time"""

[character]
success_symbol = '[👉](bold fg:color_green)'
error_symbol = '[🖕](bold fg:color_red)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'
